---

services:
  consul-server:
    image: consul
    volumes:
      - ./cfg/server/:/etc/consul.d/:z
      - /sys/fs/cgroup:/sys/fs/cgroup
    tmpfs:
      - /run
    ports:
      - 8500:8500
      - 8501:8501
      - 8600:8600/tcp
      - 8600:8600/udp
    cgroup: host

  counting:
    image: consul
    volumes:
      - ./cfg/client/consul.hcl:/etc/consul.d/consul.hcl:z
      - ../../services/counting.hcl:/etc/consul.d/counting.hcl:z
      - /sys/fs/cgroup:/sys/fs/cgroup
    tmpfs:
      - /run
    cgroup: host

  dashboard:
    image: consul
    volumes:
      - ./cfg/client/consul.hcl:/etc/consul.d/consul.hcl:z
      - ../../services/dashboard.hcl:/etc/consul.d/dashboard.hcl:z
      - /sys/fs/cgroup:/sys/fs/cgroup
    tmpfs:
      - /run
    cgroup: host

