---

services:
  consul-server:
    image: consul
    volumes:
      - ./cfg/server/:/etc/consul.d/:z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
    ports:
      - 8500:8500
      - 8501:8501
      - 8600:8600/tcp
      - 8600:8600/udp

  # External Service
  legacy-node:
    image: consul
    volumes:
      - /dev/null:/etc/consul.d/consul.hcl:z # mounting dev null to make config file empty so that Consul won't run
      - ../../services/counting.hcl:/etc/consul.d/counting.hcl:z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run

  dashboard:
    image: consul
    volumes:
      - ./cfg/client/consul.hcl:/etc/consul.d/consul.hcl:z
      - ../../services/dashboard.hcl:/etc/consul.d/dashboard.hcl:z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run

  terminating:
    image: consul
    volumes:
      - ./cfg/client/consul.hcl:/etc/consul.d/consul.hcl:z
      - /dev/zero:/etc/consul.d/terminating.env
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
